version: '3'

services:
  app:
    build: .
    depends_on:
      - redis
    links:
      - redis
    command: npm run dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      NODE_ENV: dev
      PORT: 3333
  redis:
    image: bitnami/redis:latest
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: cacheredis
